version: "3"
services:
  postgres:
    image: postgres:15.1
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  nestjs-api:
    image: nestjs-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres
    env_file:
      - .env

networks:
  postgres:
    driver: bridge